---
- name: Packages needed by ansible
  apt: name={{ packages }} state=present
  vars:
    packages:
      - pkg-config
      - python-pip
      - python3-pip

      # Needed for ansible libvirt packages
      - python3-lxml
      - python3-libvirt

- name: Install kvm and tools
  apt: name={{ packages }} state=present
  vars:
    packages:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils

- name: Disco Packages
  apt: name={{ packages }} state=present
  vars:
    packages:
      - virtinst
  when: "ansible_distribution_release == 'disco'"

- name: Creates VM directory
  file:
    path: "{{ kvm_vm_folder_path }}"
    state: directory
    owner: libvirt-qemu
    group: libvirt-qemu
    recurse: true

- name: start libvirtd
  service: name=libvirtd state=started enabled=yes
  register: libvirtd
  notify:
    - wait-for-libvirt
