image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  $PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"

cache:
  paths:
    - .cache/pip
    - .cache/pipenv
    - venv/

lint:
  before_script:
    - python -V # Print out python version for debugging
    - pip install virtualenv pipenv
    - virtualenv venv
    - source venv/bin/activate

    # --deploy enforces pipfile is up to date
    - pipenv install --dev --deploy

  script:
    - pre-commit install
    - pre-commit run -a
