---
- name: update grub
  command: update-grub

- name: wait-for-libvirt
  pause: seconds=10
  when: libvirtd.changed

- name: restart-resolved
  systemd:
    state: restarted
    daemon_reload: true
    name: systemd-resolved
