---
- name: Add local dnsmasq as a dns resolver.
  lineinfile:
    dest: "{{ kvm_resolv_conf_head_file_path }}"
    regexp: "#DNS="
    line: "DNS=192.168.122.1"
  register: nameserver_result
  notify: restart-resolved

- name: Add upstream dns mask  resolver.
  lineinfile:
    dest: "{{ kvm_resolv_conf_head_file_path }}"
    regexp: "#FallbackDNS="
    line: "FallbackDNS=10.0.0.6"
  register: nameserver_result
  notify: restart-resolved
