- include_tasks: shutdown.yml

- name: "Snapshot guest vm {{ name }} with snapshot name {{ snapshot_name | default( ansible_date_time.date ) }}"
  command: >
    virsh snapshot-create-as
    --domain {{ name }}
    --name {{ snapshot_name | default( ansible_date_time.date ) }}

- include_tasks: boot.yml
