- include_tasks: shutdown.yml

- set_fact:
     snapshot_name: "automated-snapshot_{{ snapshot_name | default( ansible_date_time.iso8601 ) }}"

- name: "Snapshot guest vm {{ name }} with snapshot name {{ snapshot_name }}"
  command: >
    virsh snapshot-create-as
    --domain {{ name }}
    --name {{ snapshot_name }}

- include_tasks: boot.yml
