image: python:3.7.3 #-alpine3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"

  # Ignore pipenv virtualenv warning
  PIPENV_VERBOSITY: -1

cache:
  paths:
    - .cache/pip
    - .cache/pipenv
    - venv/

test:
  before_script:
    # pre-commit needs git installed
    #- apk update and apk add git openssh-server

    - python -V # Print out python version for debugging
    - pip install virtualenv pipenv
    - virtualenv venv
    - source venv/bin/activate

    # --deploy enforces pipfile is up to date
    - pipenv install --dev --deploy

  script:
    - echo test!
# docker run -v /home/docker/kvm-host:/app -it python:3.7.3-alpine3.9 sh
