---
- name: "Booting guest"
  virt:
    name: "{{ name }}"
    state: running

- set_fact:
    wait_for: "{{ wait | default( true ) }}"
    wait_for_port: "{{ port | default( 22 ) }}"
    wait_for_hostname: "{{ wait_hostname | default( name ) }}"

- name: Wait for ssh to come up
  wait_for:
    host: "{{ wait_for_hostname }}"
    port: 22
    delay: 5
    timeout: 300
  when: wait_for
