---
- name: "create vm: {{ item }}"
  command: >
    virt-clone
    --original {{ kvm_base_guests_ubuntu18_04_server }}
    --name {{ item }}
    --file {{ kvm_vm_folder_path }}/{{ item }}.qcow2 }}

- name: "set vm {{ item }} to autostart"
  command: virsh autostart {{ name }}
