---
- name: Getting current guest from inventory.
  set_fact:
    guest: "{{ hostvars[inventory_hostname] }}"

- name: Guest info
  debug:
    msg: "{{ guest }}"

- name: Get facts about sibling and cloned guests.
  set_fact:
    hostname: "{{ guest['inventory_hostname'] }}"
    autostart: "{{ guest['kvm_guest_autostart'] }}"
    state: "{{ guest['kvm_guest_state'] | default( stopped ) }}"
    cloned_actively_needs: true

- name: Get facts about sibling and cloned guests.
  set_fact:
    original_vm_name: "{{ kvm_base_guests_ubuntu18_04_server | default( 'ubuntu18_04_server' ) }}"
    cloned_vm_name: "{{ guest['inventory_hostname'] }}"
    cloned_vm_os_disk: "{{ kvm_vm_folder_path }}/{{ hostname }}.qcow2"

- name: "Cloning VM {{ guest }}"
  command: >
    virt-clone
    --original {{ original_vm_name }}
    --name {{ cloned_vm_name }}
    --file {{ cloned_vm_os_disk }}
  when: cloned_actively_needs

- name: "Set cloned VM to autostart"
  command: virsh autostart {{ cloned_vm_name }}
  when: autostart

- name: Wait for cloned VM to come up under old hostname.
  include_tasks: boot.yml
  vars:
    name: "{{ cloned_vm_name }}"
    wait_for: true
    wait_for_hostname: "{{ original_vm_name }}"
