- name: Detach existing default network
  command: >
    virsh detach-interface
    --domain "{{ guest.key }}"
    --type network
    --persistent
  when: true

- name: Attach attach-device network
  command: >
    virsh attach-interface
    --domain "{{ guest.key }}"
    --type bridge
    --source "{{ guest.value.network_interface }}"
    --persistent
  when: true
