- name: "Clone guests {{ guest.name }} from base guests"
  include_tasks: util/clone.yml

- name: "If guest {{ guest.name }} reach able by base_guest hostname {{ guest.base_guest.domain }}, lets shut it down."
  command: ping -c1 "{{ guest.base_guest.domain }}"
  register: ping_result
  ignore_errors: yes

- name: "Ensure base_guest {{ guest.base_guest.name }} is shutdown before cloning guest { guest.name }}."
  import_tasks: util/shutdown.yml
  vars:
    name: "{{ guest.base_guest.name }}"

- import_tasks: util/boot.yml
  vars:
    name: "{{ guest.name }}"

- name: "Update cloned guests: {{ guest.name }} hostname"
  include_tasks: util/changehostname.yml

#- name: Resize disk
#  include_tasks: util/resize_disk.yml
#  vars:
#    #original_size:
#    expanded_size: 40GB

- import_tasks: util/snapshot.yml
  vars:
    name: "{{ guest.name }}"
    snapshot_name: "initial-snapshot"
  when: guest.name not in vms.list_vms
