---
- name: "Clone guests {{ guest.name }} from base guests"
  include_tasks: "{{ role_path }}/tasks/util/clone.yml"

- name: "Check if guest reachable"
  command: ping -c1 "{{ guest.base_guest.domain }}"
  register: ping_result
  ignore_errors: true
  when: true

- name: "Shutdown sibling guest."
  import_tasks: "{{ role_path }}/tasks/util/shutdown.yml"
  vars:
    name: "{{ guest.base_guest.name }}"

- import_tasks: "{{ role_path }}/tasks/util/boot.yml"
  vars:
    name: "{{ guest.name }}"

- name: "Update cloned guests: {{ guest.name }} hostname"
  include_tasks: util/changehostname.yml

# - name: Resize disk
#  include_tasks: util/resize_disk.yml
#  vars:
#    #original_size:
#    expanded_size: 40GB

- import_tasks: "{{ role_path }}/tasks/util/snapshot.yml"
  vars:
    name: "{{ guest.name }}"
    snapshot_name: "initial-snapshot"
  when: guest.name not in vms.list_vms
